# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Lanyon Sass
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Tweaked by <a href="https://twitter.com/benkalsky" target="_blank">@benkalsky</a>.'
url:                 hhttp://benkalsky.net/lanyon-sass
baseurl:             ''
paginate:            5

github:
  repo: https://github.com/benkalsky/lanyon-sass

sass:
  style: :expanded

# About/contact
author:
  name:              Ben Kalsky
  url:               https://twitter.com/benkalsky
  email:             benkalsky@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
